[2021-10-14 11:19:33 +0800] [1463131] [INFO] Starting gunicorn 20.1.0
[2021-10-14 11:19:33 +0800] [1463131] [INFO] Listening at: http://0.0.0.0:9090 (1463131)
[2021-10-14 11:19:33 +0800] [1463131] [INFO] Using worker: geventwebsocket.gunicorn.workers.GeventWebSocketWorker
[2021-10-14 11:19:33 +0800] [1463133] [INFO] Booting worker with pid: 1463133
[2021-10-14 11:19:33 +0800] [1463133] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/www/wwwroot/random_img/get_img_venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/www/wwwroot/random_img/get_img_venv/lib/python3.8/site-packages/gunicorn/workers/ggevent.py", line 146, in init_process
    super().init_process()
  File "/www/wwwroot/random_img/get_img_venv/lib/python3.8/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/www/wwwroot/random_img/get_img_venv/lib/python3.8/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/www/wwwroot/random_img/get_img_venv/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/www/wwwroot/random_img/get_img_venv/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/www/wwwroot/random_img/get_img_venv/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/www/wwwroot/random_img/get_img_venv/lib/python3.8/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/root/.pyenv/versions/3.8.5/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/www/wwwroot/random_img/main.py", line 7, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
[2021-10-14 11:19:33 +0800] [1463133] [INFO] Worker exiting (pid: 1463133)
[2021-10-14 11:19:33 +0800] [1463131] [INFO] Shutting down: Master
[2021-10-14 11:19:33 +0800] [1463131] [INFO] Reason: Worker failed to boot.
[2021-10-14 11:19:34 +0800] [1463145] [INFO] Starting gunicorn 20.1.0
[2021-10-14 11:19:34 +0800] [1463145] [INFO] Listening at: http://0.0.0.0:9090 (1463145)
[2021-10-14 11:19:34 +0800] [1463145] [INFO] Using worker: geventwebsocket.gunicorn.workers.GeventWebSocketWorker
[2021-10-14 11:19:34 +0800] [1463168] [INFO] Booting worker with pid: 1463168
[2021-10-14 11:19:34 +0800] [1463168] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/www/wwwroot/random_img/get_img_venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/www/wwwroot/random_img/get_img_venv/lib/python3.8/site-packages/gunicorn/workers/ggevent.py", line 146, in init_process
    super().init_process()
  File "/www/wwwroot/random_img/get_img_venv/lib/python3.8/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/www/wwwroot/random_img/get_img_venv/lib/python3.8/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/www/wwwroot/random_img/get_img_venv/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/www/wwwroot/random_img/get_img_venv/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/www/wwwroot/random_img/get_img_venv/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/www/wwwroot/random_img/get_img_venv/lib/python3.8/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/root/.pyenv/versions/3.8.5/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/www/wwwroot/random_img/main.py", line 7, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
[2021-10-14 11:19:34 +0800] [1463168] [INFO] Worker exiting (pid: 1463168)
[2021-10-14 11:19:34 +0800] [1463145] [INFO] Shutting down: Master
[2021-10-14 11:19:34 +0800] [1463145] [INFO] Reason: Worker failed to boot.
